# Generated by Django 3.2 on 2021-05-03 16:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank='True', null=True, upload_to='static/img/'),
        ),
    ]
